/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LanesIndexRouteImport } from './routes/lanes.index'
import { Route as LanesLaneIdRouteImport } from './routes/lanes.$laneId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LanesIndexRoute = LanesIndexRouteImport.update({
  id: '/lanes/',
  path: '/lanes/',
  getParentRoute: () => rootRouteImport,
} as any)
const LanesLaneIdRoute = LanesLaneIdRouteImport.update({
  id: '/lanes/$laneId',
  path: '/lanes/$laneId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lanes/$laneId': typeof LanesLaneIdRoute
  '/lanes/': typeof LanesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lanes/$laneId': typeof LanesLaneIdRoute
  '/lanes': typeof LanesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lanes/$laneId': typeof LanesLaneIdRoute
  '/lanes/': typeof LanesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/lanes/$laneId' | '/lanes/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/lanes/$laneId' | '/lanes'
  id: '__root__' | '/' | '/lanes/$laneId' | '/lanes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LanesLaneIdRoute: typeof LanesLaneIdRoute
  LanesIndexRoute: typeof LanesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lanes/': {
      id: '/lanes/'
      path: '/lanes'
      fullPath: '/lanes/'
      preLoaderRoute: typeof LanesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lanes/$laneId': {
      id: '/lanes/$laneId'
      path: '/lanes/$laneId'
      fullPath: '/lanes/$laneId'
      preLoaderRoute: typeof LanesLaneIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LanesLaneIdRoute: LanesLaneIdRoute,
  LanesIndexRoute: LanesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
