/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FlatProtoRouteImport } from './routes/flat-proto'
import { Route as MatchProtoRouteImport } from './routes/match-proto'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FlatProtoRoute = FlatProtoRouteImport.update({
  id: '/flat-proto',
  path: '/flat-proto',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchProtoRoute = MatchProtoRouteImport.update({
  id: '/match-proto',
  path: '/match-proto',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/flat-proto': typeof FlatProtoRoute
  '/match-proto': typeof MatchProtoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/flat-proto': typeof FlatProtoRoute
  '/match-proto': typeof MatchProtoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/flat-proto': typeof FlatProtoRoute
  '/match-proto': typeof MatchProtoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/flat-proto' | '/match-proto'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/flat-proto' | '/match-proto'
  id: '__root__' | '/' | '/flat-proto' | '/match-proto'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FlatProtoRoute: typeof FlatProtoRoute
  MatchProtoRoute: typeof MatchProtoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flat-proto': {
      id: '/flat-proto'
      path: '/flat-proto'
      fullPath: '/flat-proto'
      preLoaderRoute: typeof FlatProtoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match-proto': {
      id: '/match-proto'
      path: '/match-proto'
      fullPath: '/match-proto'
      preLoaderRoute: typeof MatchProtoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FlatProtoRoute: FlatProtoRoute,
  MatchProtoRoute: MatchProtoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
