/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CombatSandboxRouteImport } from './routes/combat-sandbox'
import { Route as MatchProtoRouteImport } from './routes/match-proto'
import { Route as PrototypeEmberwatchRouteImport } from './routes/prototype-emberwatch'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CombatSandboxRoute = CombatSandboxRouteImport.update({
  id: '/combat-sandbox',
  path: '/combat-sandbox',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchProtoRoute = MatchProtoRouteImport.update({
  id: '/match-proto',
  path: '/match-proto',
  getParentRoute: () => rootRouteImport,
} as any)
const PrototypeEmberwatchRoute = PrototypeEmberwatchRouteImport.update({
  id: '/prototype-emberwatch',
  path: '/prototype-emberwatch',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/combat-sandbox': typeof CombatSandboxRoute
  '/match-proto': typeof MatchProtoRoute
  '/prototype-emberwatch': typeof PrototypeEmberwatchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/combat-sandbox': typeof CombatSandboxRoute
  '/match-proto': typeof MatchProtoRoute
  '/prototype-emberwatch': typeof PrototypeEmberwatchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/combat-sandbox': typeof CombatSandboxRoute
  '/match-proto': typeof MatchProtoRoute
  '/prototype-emberwatch': typeof PrototypeEmberwatchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/combat-sandbox' | '/match-proto' | '/prototype-emberwatch'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/combat-sandbox' | '/match-proto' | '/prototype-emberwatch'
  id:
    | '__root__'
    | '/'
    | '/combat-sandbox'
    | '/match-proto'
    | '/prototype-emberwatch'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CombatSandboxRoute: typeof CombatSandboxRoute
  MatchProtoRoute: typeof MatchProtoRoute
  PrototypeEmberwatchRoute: typeof PrototypeEmberwatchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/combat-sandbox': {
      id: '/combat-sandbox'
      path: '/combat-sandbox'
      fullPath: '/combat-sandbox'
      preLoaderRoute: typeof CombatSandboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match-proto': {
      id: '/match-proto'
      path: '/match-proto'
      fullPath: '/match-proto'
      preLoaderRoute: typeof MatchProtoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototype-emberwatch': {
      id: '/prototype-emberwatch'
      path: '/prototype-emberwatch'
      fullPath: '/prototype-emberwatch'
      preLoaderRoute: typeof PrototypeEmberwatchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CombatSandboxRoute: CombatSandboxRoute,
  MatchProtoRoute: MatchProtoRoute,
  PrototypeEmberwatchRoute: PrototypeEmberwatchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
