import { defineConfig } from "eslint/config";
import tailwindConfig from "@hazard-pay/config/eslint-tailwind";

export default defineConfig([
  // Generated by the TanStack Start vite plugin — never hand-edited.
  { ignores: ["src/routeTree.gen.ts"] },
  ...tailwindConfig,
]);
